name: virtual_match
description: Proyecto de venta por catalogo - virtual_match.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.0.1+3
  google_maps_flutter: ^0.5.26+4
  location: ^3.0.0
  geolocator: ^5.3.1
  provider: ^2.0.1
  http: ^0.12.0+4
  splashscreen:
  shared_preferences: ^0.5.8
  image_picker: ^0.6.4
  url_launcher: ^5.4.2
  flutter_image_compress: ^0.6.5+1
  mime_type: ^0.2.7
  esys_flutter_share: ^1.0.2
  share: ^0.6.4+3
  flutter_webview_plugin: ^0.3.11
  webview_flutter:
  flutter_pdfview: ^1.0.0+10
  pdf_previewer: ^0.1.0
  connectivity: ^0.4.8+2
  device_preview: ^0.4.4
  curved_navigation_bar: ^0.3.2
  flare_flutter: ^2.0.1
  intl: ^0.16.0
  #simple_animations: ^1.3.6
  intro_slider: ^2.2.9
  page_transition: ^1.1.5
  imei_plugin: ^1.1.6
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.1
  animate_do: ^1.2.1
  font_awesome_flutter: ^8.8.1
  flutter_open_whatsapp: ^0.1.2
  multilevel_drawer: ^1.0.2
  file_picker: ^1.9.0+1
  auto_size_text: ^2.1.0
  getwidget: ^1.1.0
  rxdart: ^0.18.1
  path_provider:
  chewie: ^0.9.10
  flutter_swiper: ^1.1.6
  syncfusion_flutter_core: ^18.2.44
  cached_network_image: ^2.0.0
  panorama: ^0.0.2
  simple_animations: ^2.2.1
  google_fonts: ^1.1.0
  video_player: ^0.10.11+2
  photo_view: ^0.9.2
  shimmer: ^1.1.1
  flutter_linkify: ^3.1.3
  convex_bottom_bar: ^2.3.0
  animated_splash: ^1.0.0
  get: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ico/ico.png"
  adaptive_icon_background: "assets/ico/ico.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/ico/
    - assets/map/
    - assets/rrss/
    - assets/general/
    - assets/core/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: Dancing
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
    - family: Dancing2
      fonts:
        - asset: assets/fonts/DancingScript-Medium.ttf
    - family: Dancing3
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
    - family: Dancing4
      fonts:
        - asset: assets/fonts/DancingScript-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
